services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: snipshare_root
      MYSQL_DATABASE: snipshare_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
volumes:
  db_data:
